### ISSUE TITLE
API pour éteindre la Freebox

### ISSUE THREAD

**Issue by Aymkdn** [fstercq/freepybox#17]
Bonjour,

Tu sembles très bien informé sur les API de Free qui ne sont pas encore documentées !

Sais-tu s'il existe une API pour éteindre la Freebox ? J'ai vu les API Player qui permettent de zapper sur une chaine (tout en allumant la Freebox) en utilisant `player/{player_id}/api/{player_api_version}/control/open`, et donc je me demandais si quelque chose d'équivalent existe pour l'éteindre ?

Merci 🙏

**Comment by fstercq** [comment]
Bonjour Aymeric,
Merci pour ton email,
Cela fait très longtemps que je n'ai plus suivi les API Freebox (je ne
participe plus depuis plusieurs années au projet freepybox).
Désolé de ne pas pouvoir te renseigner.
A+
Florian

**Comment by Aymkdn** [comment]
Ah, dommage… Merci quand même !
