### ISSUE TITLE
Release a new version on PyPI

### ISSUE THREAD

**Issue by stilllman** [fstercq/freepybox#4]
Would it be possible to make a new release of this library on PyPI? I'm using it in a component for Home Assistant (see [this PR](https://github.com/home-assistant/home-assistant/pull/12727)) and they require all third party dependencies to be fetchable from PyPI. Since you've merged a few changes lately, would you mind publishing a new version?

**Comment by ylecuyer** [comment]
Yes please. I want to beta test the PR from @stilllman but I can't while the new version of freepybox isn't available from PyPI

**Comment by stilllman** [comment]
I've ended up implementing the Home Assistant component with the asynchronous fork I made.
